### PR TITLE
style: update employees job titles

### PR DESCRIPTION
**Pull request by jeremylgn**
Self explanatory.

### CODE REVIEW

**Review by SonnevilleDamien — APPROVED** [review]

**Review by AnjaMis — APPROVED** [review]
👌🏻

**Review by MdechampG — APPROVED** [review]

**Review by ccamel — CHANGES_REQUESTED** [review]
Just a minor remark, the commit prefix should be 'fix', as the wiki content is feature. It would be great if you could amend the message. 🙏

**Comment by jeremylgn** [comment]
> Just a minor remark, the commit prefix should be 'fix', as the wiki content is feature. It would be great if you could amend the message. 🙏

Done :heavy_check_mark:

**Review by ccamel — APPROVED** [review]
Great! :+1:

**Pull request merged**
